package com.scrcu.ebank.ebap.batch.bean.dto;

import com.scrcu.ebank.ebap.common.beans.CommonDTO;

public class ParternBaseInfo extends CommonDTO{
   
    private String parternId;

    private String parternType;

    private String parternCode;

    private String parternName;

    private String name;

    private String phone;

    private String accountType;

    private String accountNo;

    private String accountName;

    private String accountOrg;

    private Short settleDay;

    private String monthDay;

    private String qualifiType;

    private String certNo;

    private String artifName;

    private String artifPhone;

    private String artifCardType;

    private String artifCardNo;

    private String cardStartDate;

    private String cardEndDate;

    private String createTlr;

    private String createTime;

    private String updTlr;

    private String updTime;

    private String cooperationPath;
    
    private String parternStatus;

    private String mchtNo;
    private String openClientId;

    public String getMchtNo() {
        return mchtNo;
    }

    public void setMchtNo(String mchtNo) {
        this.mchtNo = mchtNo;
    }

    public String getParternId() {
        return parternId;
    }

    public void setParternId(String parternId) {
        this.parternId = parternId == null ? null : parternId.trim();
    }

    public String getParternType() {
        return parternType;
    }

    public void setParternType(String parternType) {
        this.parternType = parternType == null ? null : parternType.trim();
    }

    public String getParternCode() {
        return parternCode;
    }

    public void setParternCode(String parternCode) {
        this.parternCode = parternCode == null ? null : parternCode.trim();
    }

    public String getParternName() {
        return parternName;
    }

    public void setParternName(String parternName) {
        this.parternName = parternName == null ? null : parternName.trim();
    }

    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.NAME
     *
     * @param name the value for PARTERN_INFO.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.PHONE
     *
     * @return the value of PARTERN_INFO.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.PHONE
     *
     * @param phone the value for PARTERN_INFO.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.ACCOUNT_TYPE
     *
     * @return the value of PARTERN_INFO.ACCOUNT_TYPE
     *
     * @mbggenerated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.ACCOUNT_TYPE
     *
     * @param accountType the value for PARTERN_INFO.ACCOUNT_TYPE
     *
     * @mbggenerated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.ACCOUNT_NO
     *
     * @return the value of PARTERN_INFO.ACCOUNT_NO
     *
     * @mbggenerated
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.ACCOUNT_NO
     *
     * @param accountNo the value for PARTERN_INFO.ACCOUNT_NO
     *
     * @mbggenerated
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.ACCOUNT_NAME
     *
     * @return the value of PARTERN_INFO.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.ACCOUNT_NAME
     *
     * @param accountName the value for PARTERN_INFO.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.ACCOUNT_ORG
     *
     * @return the value of PARTERN_INFO.ACCOUNT_ORG
     *
     * @mbggenerated
     */
    public String getAccountOrg() {
        return accountOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.ACCOUNT_ORG
     *
     * @param accountOrg the value for PARTERN_INFO.ACCOUNT_ORG
     *
     * @mbggenerated
     */
    public void setAccountOrg(String accountOrg) {
        this.accountOrg = accountOrg == null ? null : accountOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.SETTLE_DAY
     *
     * @return the value of PARTERN_INFO.SETTLE_DAY
     *
     * @mbggenerated
     */
    public Short getSettleDay() {
        return settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.SETTLE_DAY
     *
     * @param settleDay the value for PARTERN_INFO.SETTLE_DAY
     *
     * @mbggenerated
     */
    public void setSettleDay(Short settleDay) {
        this.settleDay = settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.MONTH_DAY
     *
     * @return the value of PARTERN_INFO.MONTH_DAY
     *
     * @mbggenerated
     */
    public String getMonthDay() {
        return monthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.MONTH_DAY
     *
     * @param monthDay the value for PARTERN_INFO.MONTH_DAY
     *
     * @mbggenerated
     */
    public void setMonthDay(String monthDay) {
        this.monthDay = monthDay == null ? null : monthDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.QUALIFI_TYPE
     *
     * @return the value of PARTERN_INFO.QUALIFI_TYPE
     *
     * @mbggenerated
     */
    public String getQualifiType() {
        return qualifiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.QUALIFI_TYPE
     *
     * @param qualifiType the value for PARTERN_INFO.QUALIFI_TYPE
     *
     * @mbggenerated
     */
    public void setQualifiType(String qualifiType) {
        this.qualifiType = qualifiType == null ? null : qualifiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.CERT_NO
     *
     * @return the value of PARTERN_INFO.CERT_NO
     *
     * @mbggenerated
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.CERT_NO
     *
     * @param certNo the value for PARTERN_INFO.CERT_NO
     *
     * @mbggenerated
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo == null ? null : certNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.ARTIF_NAME
     *
     * @return the value of PARTERN_INFO.ARTIF_NAME
     *
     * @mbggenerated
     */
    public String getArtifName() {
        return artifName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.ARTIF_NAME
     *
     * @param artifName the value for PARTERN_INFO.ARTIF_NAME
     *
     * @mbggenerated
     */
    public void setArtifName(String artifName) {
        this.artifName = artifName == null ? null : artifName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.ARTIF_PHONE
     *
     * @return the value of PARTERN_INFO.ARTIF_PHONE
     *
     * @mbggenerated
     */
    public String getArtifPhone() {
        return artifPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.ARTIF_PHONE
     *
     * @param artifPhone the value for PARTERN_INFO.ARTIF_PHONE
     *
     * @mbggenerated
     */
    public void setArtifPhone(String artifPhone) {
        this.artifPhone = artifPhone == null ? null : artifPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.ARTIF_CARD_TYPE
     *
     * @return the value of PARTERN_INFO.ARTIF_CARD_TYPE
     *
     * @mbggenerated
     */
    public String getArtifCardType() {
        return artifCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.ARTIF_CARD_TYPE
     *
     * @param artifCardType the value for PARTERN_INFO.ARTIF_CARD_TYPE
     *
     * @mbggenerated
     */
    public void setArtifCardType(String artifCardType) {
        this.artifCardType = artifCardType == null ? null : artifCardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.ARTIF_CARD_NO
     *
     * @return the value of PARTERN_INFO.ARTIF_CARD_NO
     *
     * @mbggenerated
     */
    public String getArtifCardNo() {
        return artifCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.ARTIF_CARD_NO
     *
     * @param artifCardNo the value for PARTERN_INFO.ARTIF_CARD_NO
     *
     * @mbggenerated
     */
    public void setArtifCardNo(String artifCardNo) {
        this.artifCardNo = artifCardNo == null ? null : artifCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.CARD_START_DATE
     *
     * @return the value of PARTERN_INFO.CARD_START_DATE
     *
     * @mbggenerated
     */
    public String getCardStartDate() {
        return cardStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.CARD_START_DATE
     *
     * @param cardStartDate the value for PARTERN_INFO.CARD_START_DATE
     *
     * @mbggenerated
     */
    public void setCardStartDate(String cardStartDate) {
        this.cardStartDate = cardStartDate == null ? null : cardStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.CARD_END_DATE
     *
     * @return the value of PARTERN_INFO.CARD_END_DATE
     *
     * @mbggenerated
     */
    public String getCardEndDate() {
        return cardEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.CARD_END_DATE
     *
     * @param cardEndDate the value for PARTERN_INFO.CARD_END_DATE
     *
     * @mbggenerated
     */
    public void setCardEndDate(String cardEndDate) {
        this.cardEndDate = cardEndDate == null ? null : cardEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.CREATE_TLR
     *
     * @return the value of PARTERN_INFO.CREATE_TLR
     *
     * @mbggenerated
     */
    public String getCreateTlr() {
        return createTlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.CREATE_TLR
     *
     * @param createTlr the value for PARTERN_INFO.CREATE_TLR
     *
     * @mbggenerated
     */
    public void setCreateTlr(String createTlr) {
        this.createTlr = createTlr == null ? null : createTlr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.CREATE_TIME
     *
     * @return the value of PARTERN_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.CREATE_TIME
     *
     * @param createTime the value for PARTERN_INFO.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.UPD_TLR
     *
     * @return the value of PARTERN_INFO.UPD_TLR
     *
     * @mbggenerated
     */
    public String getUpdTlr() {
        return updTlr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.UPD_TLR
     *
     * @param updTlr the value for PARTERN_INFO.UPD_TLR
     *
     * @mbggenerated
     */
    public void setUpdTlr(String updTlr) {
        this.updTlr = updTlr == null ? null : updTlr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.UPD_TIME
     *
     * @return the value of PARTERN_INFO.UPD_TIME
     *
     * @mbggenerated
     */
    public String getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.UPD_TIME
     *
     * @param updTime the value for PARTERN_INFO.UPD_TIME
     *
     * @mbggenerated
     */
    public void setUpdTime(String updTime) {
        this.updTime = updTime == null ? null : updTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PARTERN_INFO.COOPERATION_PATH
     *
     * @return the value of PARTERN_INFO.COOPERATION_PATH
     *
     * @mbggenerated
     */
    public String getCooperationPath() {
        return cooperationPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PARTERN_INFO.COOPERATION_PATH
     *
     * @param cooperationPath the value for PARTERN_INFO.COOPERATION_PATH
     *
     * @mbggenerated
     */
    public void setCooperationPath(String cooperationPath) {
        this.cooperationPath = cooperationPath == null ? null : cooperationPath.trim();
    }

	public String getParternStatus() {
		return parternStatus;
	}

	public void setParternStatus(String parternStatus) {
		this.parternStatus = parternStatus;
	}

    public String getOpenClientId() {
        return openClientId;
    }

    public void setOpenClientId(String openClientId) {
        this.openClientId = openClientId;
    }
}
